services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=booking_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d booking_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/booking_db
      - PGPASSWORD=password
    command: >
      sh -c "./wait-for-it.sh db:5432 --timeout=30 --strict -- alembic upgrade head && psql -h db -p 5432 -U user -d booking_db -f seed.sql && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./backend/seed.sql:/app/seed.sql
      - ./backend/wait-for-it.sh:/app/wait-for-it.sh
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
volumes:
  postgres_data:
